### ISSUE TITLE
index.d.ts is not a module

### ISSUE THREAD

**Issue by piq9117** [unindented/custom-immutable-matchers#35]
First of all,
Thank you for this library.
Im importing it like it says in the readme
```
import * as matchers from 'jasmine-immutable-matchers';
```
I'm still getting this even after the tsconfig.json setup. 
```
node_modules/jasmine-immutable-matchers/index.d.ts is not a module
```
Does it matter if I'm using @types?

**Comment by piq9117** [comment]
hmm.. i'll just do 
```
const matchers = require('jasmine-immutable-matchers')
```

**Comment by unindented** [comment]
@piq9117 Sorry for the slow response. What version of `jasmine-immutable-matchers` are you using?
