### ISSUE TITLE
No longer works with Jest 21+

### ISSUE THREAD

**Issue by jamesmoss** [unindented/custom-immutable-matchers#39]
Jest recently made a change that requires all matchers to return a function that returns a message string rather than a string itself.

https://github.com/facebook/jest/issues/3921

Attempting to use this lib with a version of Jest >= 21 will give you something similar to the error below if any test that uses these matchers fails:

```
 FAIL  test/reducers/appReducer.test.js
  ● app reducer › should return the initial state

    TypeError: message is not a function

      at getMessage (node_modules/expect/build/index.js:106:16)
      at Object.throwingMatcher [as toEqualImmutable] (node_modules/expect/build/index.js:216:23)
      at Object.<anonymous> (test/reducers/appReducer.test.js:9:3)
```

**Comment by unindented** [comment]
Fixed by @njlr.

**Comment by unindented** [comment]
`v2.0.0` should be compatible with Jest `>=21`. Let me know how it works for you.
